# Generated by Django 2.2 on 2019-04-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
