# Generated by Django 2.2 on 2019-04-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_delete_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=200)),
                ('per', models.CharField(max_length=200)),
                ('depart', models.CharField(max_length=200)),
            ],
        ),
    ]
